# -*- coding: utf-8 -*-
"""run_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQjG9JwuRG_hXHUqffVicHPkAtcqEfJE
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ai-energy-predictor

# Verify GPU is active & only proceed if outputs True
import torch
print(torch.cuda.is_available())

# Only ran once until models were saved

# !python setup.py --n-samples 5000 --epochs 30

!python app.py